Student assignments
kat-h6/fivelines pull request #2
Opened 2021-06-10 16:45 UTC by Sapideh1071

I have created a new student assignment page, and an index over the assignments a student has or has had

2021-06-10 16:51 UTC, kat-h6 requested changes
looks awesome! just that one thing, and I know you're still working on that show page

2021-06-10 16:51 UTC, kat-h6 commented on app/controllers/users_controller.rb
> +    puts "My assignments"
maybe you can take out these puts statements now :D

2021-06-10 18:06 UTC, kat-h6 reviewed
looks awesome!

2021-06-10 18:06 UTC, merged

2021-06-11 15:45 UTC, Sapideh1071 commented
I tried to pull the latest master, but I have a problem with the Gemlock
file. Second time this is happening.

tor. 10. jun. 2021 kl. 20:06 skrev Katharine Hao ***@***.***>:

> Merged #2 <https://github.com/kat-h6/fivelines/pull/2> into master.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kat-h6/fivelines/pull/2#event-4873118091>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASCYDWWT5KZ5ZHY5OK5KSH3TSD5KNANCNFSM46O4RDXA>
> .
>